apiVersion: v1
kind: Pod
metadata:
  name: Leemysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_DATABASE
      value: "root"
    - password: MYSQL_ROOT_PASSWORD
      value: "root"
  